### DISCUSSION TITLE
How to deploy the cache using docker?

### DISCUSSION THREAD

**Discussion by ranile** [ducktors/turborepo-remote-cache#172] [Q&A]
I don't see anything about a published docker image in a documentation. Is there one? If so, where can I find it?

What's needed to deploy it? I would like to host my own instance on a private server

**Comment by timokoessler** [comment]
This is described in the documentation: https://ducktors.github.io/turborepo-remote-cache/deployment-environments#deploy-on-docker

For example, a Docker Compose file might look like this:

```yaml
version: '3'
services:
  turbo-cache:
    image: ducktors/turborepo-remote-cache
    restart: always
    container_name: turbo-cache
    ports:
      - "172.17.0.1:8092:3000" # Change
    environment:
      - STORAGE_PROVIDER=local
      - TURBO_TOKEN=... # Set auth token
```
