### DISCUSSION TITLE
How to know if Cache server is working?

### DISCUSSION THREAD

**Discussion by NorkzYT** [ducktors/turborepo-remote-cache#84] [Q&A] [answered]
Hello,

Hope anyone that reads this is having a great day!

I only have the following line in the `Docker Container` logs, and no other log appears when I use the remote cache.
```
54896/11/01 01:17PM 30 Server listening at http://0.0.0.0:3000 | severity=INFO pid=6 hostname=turborepo-remote-cache
```

How do I know when I run the npm script `build` command, the action is importing the cache, and/or exporting it?

Is the `STORAGE_PATH` environmental variable correctly used along with `volumes`?

The following contains the contents of the `TurboRepo Remote Cache` `docker-compose.yml` file.
```yml
version: '3.9'
services:

  turborepo-remote-cache:
    image: fox1t/turborepo-remote-cache:1.8.0
    container_name: turborepo-remote-cache
    hostname: turborepo-remote-cache
    environment:
      - NODE_ENV=production
      - TURBO_TOKEN='xxx'
      - LOG_LEVEL=debug
      - STORAGE_PROVIDER=local
      - STORAGE_PATH=/tmp
    volumes:
      - /mnt/appdata/repo-team/turborepo-remote-cache/tmp:/tmp
    ports:
      - 3535:3000
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
```
