### ISSUE TITLE
HTTP Error 412 while using recent Turbo versions

### ISSUE THREAD

**Issue by trappar** [ducktors/turborepo-remote-cache#323]
## 🐛 Bug Report

I updated Turbo from `1.10.16` to `1.12.5` today and started seeing this in CI:

```
 WARNING  failed to contact remote cache: Error making HTTP request: HTTP status client error (412 Precondition Failed) for url (http://0.0.0.0:45045/v8/artifacts/e946449d9e73b6d1?slug=ci)
 ```

There is some discussion around this in [this turbo issue](https://github.com/vercel/turbo/issues/6765), where people mention that this is likely due to using this remote cache server along with S3 specifically. 

## To Reproduce

I doubt that it will be possible for me to create reproduction instructions / repo for this issue considering that others have failed to reliably reproduce this in the thread above.

## Expected behavior

To not get the http status errors.

## Your Environment

- Using this package with my [GH action](https://github.com/trappar/turborepo-remote-cache-gh-action). I'm specifically using `trappar/turborepo-remote-cache-gh-action@v2`, which is a new version I've been working on in order to support the up-to-date version of this package.
- Turbo version `1.12.5`
- Seeing the failures in CI (I don't use this server locally) where I'm using `ubuntu-latest`
- Server is configured to connect to an S3 bucket

**Comment by spacedawwwg** [comment]
we've been having the same issue using Azure. Locked in at turbo v1.10 for now until we have time to fully investigate

**Comment by matteovivona** [comment]
Super weird. We're using a remote-cache server and Turbo 1.12.5 in other projects, and so far, we haven't had any problems at all

<img width="1921" alt="Screenshot 2024-03-21 at 10 15 10" src="https://github.com/ducktors/turborepo-remote-cache/assets/6388707/1032c87e-3d20-42b0-a9ed-b0b911caa3bd">

**Comment by trappar** [comment]
I've found what is causing this in my particular case.

I have two different workflows. I was only seeing this issue appear in one of them.

Both of them utilize my GH Action to start a cache server like this:

```yaml
- uses: trappar/turborepo-remote-cache-gh-action@v2
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  with:
    storage-provider: s3
    storage-path: turborepo-cache
```

However, the one that was failing had the following proceeding it:
```yaml
- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/[REDACTED]
    aws-region: us-east-1
```

If I simply switch the order of these so that the remote cache server starts _**before**_ configuring AWS credentials, then the error disappears.

So I'm not actually sure if this is a bug or not. Which credentials should take precedence? I'd assume env variables, but it looks like I'm wrong. I'm not actually 100% sure what the output of that aws action is, but it looks like it's taking over, and I'm fairly certain whatever credentials those are don't actually have permission to view the S3 bucket I'm telling the cache server to use.

Can someone who knows more about AWS than me help here?
