### ISSUE TITLE
Health check without auth header

### ISSUE THREAD

**Issue by jazmon** [ducktors/turborepo-remote-cache#85]
## 🚀 Feature Proposal

Create a (or modify the existing) health check endpoint that is not protected with the authorization header.

## Motivation

Without this, it's not possible to scale the service behind an AWS ALB with a health check as ALB doesn't support passing headers.

## Example

AWS ALB health checks

**Comment by Atrax1** [comment]
We currently use : 
```
    alb.ingress.kubernetes.io/healthcheck-path: '/v8/artifacts/status'
    alb.ingress.kubernetes.io/success-codes: '200,400'
```
and on deployment.yaml
```
          livenessProbe:
            httpGet:
              path: /v8/artifacts/status
              port: http
              httpHeaders:
                - name: Authorization
                  value: {{ printf "Bearer %s" .Values.envs.turboToken }}
          readinessProbe:
            httpGet:
              path: /v8/artifacts/status
              port: http
              httpHeaders:
                - name: Authorization
                  value: {{ printf "Bearer %s" .Values.envs.turboToken }}
```
